import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./_components/ClientLayout";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Me",
  icons: {
    icon: "/computer.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="font-inter bg-[#1F1F1F] h-full w-full flex justify-center relative overflow-y-hidden">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
