import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/header/Header";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className="font-inter bg-[#2A2B2A] h-full w-full flex justify-center relative "
      >
        <Header />
        <main className=" lg:w-5xl w-full">{children}</main>
      </body>
    </html>
  );
}
