import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/footer/Footer";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className="font-inter bg-[#1F1F1F] h-full w-full flex justify-center relative "
      >
        <Header />
        <main className="h-fit lg:w-5xl w-full overflow-x-hidden ">
          {children} 
          <Footer />
        </main>
      </body>
    </html>
  );
}
